
--[[###
This file auto-generated by script of https://github.com/ZwerOxotnik/factorio-decals
Add "decals >= 2.0.0" in your dependencies
This file should be in root folder of a mod!!!
]]--###


local data_stage_data = {
	["A"] = {
		filename = "__multi-template-mod__/scenarios/template/decals/A.png",
		width=143, height=200,
	},
}


for name, _data in pairs(data_stage_data) do
	_data.type = _data.type or "sprite"
	_data.name = _data.name or (name .. "_decal")
end


if decals_mod then
	return data_stage_data
else
	local control_stage_data = {}
	for name, _data in pairs(data_stage_data) do
		if _data.type == "sprite" then
			control_stage_data[name] = _data.name
		else
			control_stage_data[name] = _data.type .. "/" .. _data.name
		end
	end
	return control_stage_data
end
