
--[[###
This file auto-generated by script of https://github.com/ZwerOxotnik/factorio-decals
WARNING: This file should be in scenario folder of a mod and should renames as "decal_list.lua"!!!
WARNING: path to images probably is not correct. Read https://lua-api.factorio.com/latest/Concepts.html#SpritePath
]]--###


return {
	["A"] = "file/decals/A",
}
